using Content.Client._WF.Audio.InternetSound;
using Content.Shared._WF.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Administration.UI.InternetSound;

/// <summary>
/// Admin panel for internet sounds: paste a link, play it to everyone, or stop it.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class InternetSoundAdminWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly InternetSoundSystem _internetSound;

    public InternetSoundAdminWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _internetSound = _entityManager.System<InternetSoundSystem>();
        _internetSound.StatusReceived += OnStatus;
        OnClose += () => _internetSound.StatusReceived -= OnStatus;

        PlayButton.OnPressed += _ => Play();
        UrlEdit.OnTextEntered += _ => Play();
        StopButton.OnPressed += _ => _consoleHost.ExecuteCommand(WolfgateAdminCommands.StopInternetSound);
    }

    private void Play()
    {
        // Quotes would break the command line; links never need them.
        var url = UrlEdit.Text.Trim().Replace("\"", string.Empty);
        if (url.Length == 0)
            return;

        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.PlayInternetSound} \"{url}\"");
    }

    private void OnStatus(string message, bool isError)
    {
        StatusLabel.Text = message;
        StatusLabel.FontColorOverride = isError ? Color.Red : null;
    }
}
