using System.Linq;
using Content.Client._Common.Consent;
using Content.Client._Common.Consent.UI;
using Content.Shared._Common.CCVar;
using Content.Shared._Common.Consent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Options.UI.Tabs;

/// <summary>
/// The OOC consent preferences, as a tab in Game Options instead of a window of their own.
/// Consent is stored per player on the server rather than in a CVar, so this tab keeps its own Save
/// button rather than joining the options window's shared Apply row.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WolfgateConsentTab : Control
{
    [Dependency] private IClientConsentManager _consentManager = default!;
    [Dependency] private IConfigurationManager _configManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly List<ConsentToggleControl> _toggles = new();

    public WolfgateConsentTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SaveConsentSettings.OnPressed += _ =>
        {
            SaveConsentSettings.Disabled = true;
            _consentManager.UpdateConsent(GetSettings());
        };

        ConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-window-freetext-placeholder"));
        ConsentFreetext.OnTextChanged += _ => UnsavedChanges();

        _consentManager.OnServerDataLoaded += Refresh;
    }

    /// <summary>
    /// Rebuilds the toggles and reloads the saved values. Called whenever the options window opens, so a
    /// toggle prototype added by a different server still shows up.
    /// </summary>
    public void Refresh()
    {
        var loaded = _consentManager.HasLoaded;
        ConsentContent.Visible = loaded;
        UnavailableLabel.Visible = !loaded;

        if (!loaded)
            return;

        BuildToggles();
        LoadValues();
    }

    private void BuildToggles()
    {
        var wanted = _prototypeManager.EnumeratePrototypes<ConsentTogglePrototype>()
            .OrderBy(x => x.SortKey)
            .ToList();

        if (_toggles.Count == wanted.Count &&
            _toggles.Select(t => t.ConsentToggleProtoId).SequenceEqual(wanted.Select(p => (ProtoId<ConsentTogglePrototype>) p.ID)))
        {
            return;
        }

        ConsentSettings.DisposeAllChildren();
        _toggles.Clear();

        foreach (var toggle in wanted)
        {
            var control = new ConsentToggleControl(toggle);
            control.OnStateChange += _ => UnsavedChanges();
            _toggles.Add(control);
            ConsentSettings.AddChild(control);
        }
    }

    private void LoadValues()
    {
        var consent = _consentManager.GetConsentSettings();
        ConsentFreetext.TextRope = new Rope.Leaf(consent.Freetext);

        foreach (var toggle in _toggles)
        {
            // The server only stores toggles that are on, so anything absent is off.
            toggle.SetState(consent.Toggles.TryGetValue(toggle.ConsentToggleProtoId, out var state) ? state : "off");
        }

        SaveConsentSettings.Disabled = true;
        SaveLabel.Text = string.Empty;
    }

    private PlayerConsentSettings GetSettings()
    {
        var toggles = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();
        foreach (var toggle in _toggles)
            toggles[toggle.ConsentToggleProtoId] = toggle.State;

        return new PlayerConsentSettings(Rope.Collapse(ConsentFreetext.TextRope), toggles);
    }

    private void UnsavedChanges()
    {
        var maxLength = _configManager.GetCVar(ConsentSystemCCVars.ConsentFreetextMaxLength);
        var length = Rope.Collapse(ConsentFreetext.TextRope).Length;

        if (length > maxLength)
        {
            SaveLabel.Text = Loc.GetString("consent-window-char-limit-warning", ("length", length), ("maxLength", maxLength));
            SaveConsentSettings.Disabled = true;
            return;
        }

        SaveLabel.Text = Loc.GetString("consent-window-unsaved-changes");
        SaveConsentSettings.Disabled = false;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _consentManager.OnServerDataLoaded -= Refresh;

        base.Dispose(disposing);
    }
}
