using System.Linq;
using Content.Client._WF.Administration.Ert;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared._WF.Administration.Ert;
using Content.Shared.Access;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Administration.UI.Ert;

/// <summary>
/// Admin ERT Builder: team name and briefing, size, outfits, ID titles and access, allowed species and ship.
/// The server spawns the ship and ghost roles; ghosts then pick them from the ghost role menu.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ErtBuilderWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private const string DefaultMemberOutfit = "ERTSecurityGearEVA";
    private const string DefaultLeaderOutfit = "ERTLeaderGearEVA";

    private readonly ErtSystem _ert;
    private readonly List<string> _outfits;
    private readonly List<VesselPrototype> _vessels;
    private readonly Dictionary<string, CheckBox> _species = new();
    private readonly Dictionary<string, CheckBox> _access = new();

    // Prototype ids shown in each dropdown, by item id. Empty means "same as members" or "no ship".
    private readonly List<string> _memberShown = new();
    private readonly List<string> _leaderShown = new();
    private readonly List<string> _shipShown = new();

    public ErtBuilderWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _ert = _entityManager.System<ErtSystem>();
        _ert.ResultReceived += OnResult;
        OnClose += () => _ert.ResultReceived -= OnResult;

        MembersSpin.IsValid = value => value is >= 1 and <= ErtLimits.MaxMembers;
        MembersSpin.InitDefaultButtons();
        MembersSpin.Value = 4;

        _outfits = GetOutfits();
        _vessels = _prototypeManager.EnumeratePrototypes<VesselPrototype>()
            .Where(vessel => !vessel.Abstract)
            .OrderBy(vessel => vessel.Name, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        FillOutfits(MemberOutfitSelect, _memberShown, string.Empty, false, DefaultMemberOutfit);
        FillOutfits(LeaderOutfitSelect, _leaderShown, string.Empty, true, DefaultLeaderOutfit);
        FillShips(string.Empty, string.Empty);
        BuildSpecies();
        BuildAccess();
        UpdateTitlePlaceholders();

        MemberOutfitSearch.OnTextChanged += args =>
            FillOutfits(MemberOutfitSelect, _memberShown, args.Text, false, Selected(MemberOutfitSelect, _memberShown));
        LeaderOutfitSearch.OnTextChanged += args =>
            FillOutfits(LeaderOutfitSelect, _leaderShown, args.Text, true, Selected(LeaderOutfitSelect, _leaderShown));
        ShipSearch.OnTextChanged += args => FillShips(args.Text, Selected(ShipSelect, _shipShown));

        MemberOutfitSelect.OnItemSelected += args => MemberOutfitSelect.SelectId(args.Id);
        LeaderOutfitSelect.OnItemSelected += args => LeaderOutfitSelect.SelectId(args.Id);
        ShipSelect.OnItemSelected += args => ShipSelect.SelectId(args.Id);

        TeamNameEdit.OnTextChanged += _ => UpdateTitlePlaceholders();
        GenericHumansCheck.OnToggled += args => SetSpeciesEnabled(!args.Pressed);
        SpawnButton.OnPressed += _ => Spawn();
    }

    /// <summary>
    /// The species filter doesn't apply when everyone is a random human.
    /// </summary>
    private void SetSpeciesEnabled(bool enabled)
    {
        foreach (var box in _species.Values)
        {
            box.Disabled = !enabled;
        }
    }

    /// <summary>
    /// Starting gear that isn't part of a loadout, ERT gear first. Same filter as Set Outfit.
    /// </summary>
    private List<string> GetOutfits()
    {
        var loadoutGears = _prototypeManager.EnumeratePrototypes<LoadoutPrototype>()
            .Select(loadout => loadout.StartingGear.ToString())
            .ToHashSet();

        return _prototypeManager.EnumeratePrototypes<StartingGearPrototype>()
            .Where(gear => !gear.Abstract && !loadoutGears.Contains(gear.ID))
            .Select(gear => gear.ID)
            .OrderBy(id => id.StartsWith("ERT") ? 0 : 1)
            .ThenBy(id => id, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>
    /// Refills an outfit dropdown from the search text, keeping the selection if it's still listed.
    /// </summary>
    private void FillOutfits(OptionButton button, List<string> shown, string filter, bool includeSame, string keep)
    {
        button.Clear();
        shown.Clear();

        if (includeSame)
        {
            button.AddItem(Loc.GetString("wf-ert-same-as-members"), shown.Count);
            shown.Add(string.Empty);
        }

        var search = filter.Trim().ToLowerInvariant();
        foreach (var id in _outfits)
        {
            if (search.Length > 0 && !id.ToLowerInvariant().Contains(search))
                continue;

            button.AddItem(id, shown.Count);
            shown.Add(id);
        }

        var index = shown.IndexOf(keep);
        if (index >= 0)
            button.SelectId(index);
    }

    private void FillShips(string filter, string keep)
    {
        ShipSelect.Clear();
        _shipShown.Clear();

        ShipSelect.AddItem(Loc.GetString("wf-ert-no-ship"), _shipShown.Count);
        _shipShown.Add(string.Empty);

        var search = filter.Trim().ToLowerInvariant();
        foreach (var vessel in _vessels)
        {
            if (search.Length > 0
                && !vessel.Name.ToLowerInvariant().Contains(search)
                && !vessel.ID.ToLowerInvariant().Contains(search))
                continue;

            var size = Loc.GetString($"shipyard-console-category-{vessel.Category}");
            ShipSelect.AddItem($"{vessel.Name} ({size})", _shipShown.Count);
            _shipShown.Add(vessel.ID);
        }

        var index = _shipShown.IndexOf(keep);
        ShipSelect.SelectId(index >= 0 ? index : 0);
    }

    private static string Selected(OptionButton button, List<string> shown)
    {
        var id = button.SelectedId;
        return id >= 0 && id < shown.Count ? shown[id] : string.Empty;
    }

    private void BuildSpecies()
    {
        var species = _prototypeManager.EnumeratePrototypes<SpeciesPrototype>()
            .Where(proto => proto.RoundStart)
            .OrderBy(proto => Loc.GetString(proto.Name));

        foreach (var proto in species)
        {
            var box = new CheckBox { Text = Loc.GetString(proto.Name) };
            _species[proto.ID] = box;
            SpeciesGrid.AddChild(box);
        }
    }

    private void BuildAccess()
    {
        foreach (var group in _prototypeManager.EnumeratePrototypes<AccessGroupPrototype>().OrderBy(group => group.GetAccessGroupName()))
        {
            var box = new CheckBox { Text = group.GetAccessGroupName(), ToolTip = group.ID };
            _access[group.ID] = box;
            AccessGrid.AddChild(box);
        }
    }

    /// <summary>
    /// Shows the titles the server will use if the fields are left empty.
    /// </summary>
    private void UpdateTitlePlaceholders()
    {
        var team = TeamName();
        LeaderTitleEdit.PlaceHolder = Loc.GetString("wf-ert-default-leader-title", ("team", team));
        MemberTitleEdit.PlaceHolder = Loc.GetString("wf-ert-default-member-title", ("team", team));
    }

    private string TeamName()
    {
        var team = TeamNameEdit.Text.Trim();
        return team.Length > 0 ? team : Loc.GetString("wf-ert-team-name-placeholder");
    }

    private void Spawn()
    {
        var config = new ErtConfig
        {
            TeamName = TeamName(),
            Briefing = BriefingEdit.Text.Trim(),
            Members = MembersSpin.Value,
            HasLeader = LeaderCheck.Pressed,
            LeaderTitle = LeaderTitleEdit.Text.Trim(),
            MemberTitle = MemberTitleEdit.Text.Trim(),
            MemberOutfit = Selected(MemberOutfitSelect, _memberShown),
            LeaderOutfit = Selected(LeaderOutfitSelect, _leaderShown),
            Species = _species.Where(pair => pair.Value.Pressed).Select(pair => pair.Key).ToList(),
            GenericHumans = GenericHumansCheck.Pressed,
            AccessGroups = _access.Where(pair => pair.Value.Pressed).Select(pair => pair.Key).ToList(),
            KeepOutfitAccess = KeepAccessCheck.Pressed,
            Vessel = Selected(ShipSelect, _shipShown),
        };

        _ert.RequestSpawn(config);
    }

    private void OnResult(string message, bool isError)
    {
        StatusLabel.Text = message;
        StatusLabel.FontColorOverride = isError ? Color.Red : null;
    }
}
