using Content.Shared._WF.Administration.Ert;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.Administration.UI.Ert;

/// <summary>
/// Shown to every ghost when an admin calls an ERT: team, briefing, and buttons to join the draw.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ErtPromptWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _console = default!;

    /// <summary>
    /// True when signing up for the leader place.
    /// </summary>
    public event Action<bool>? SignUpPressed;

    public ErtPromptWindow(ErtCalledEvent call)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TeamLabel.Text = call.Team;
        BriefingLabel.SetMessage(FormattedMessage.FromUnformatted(call.Briefing));
        PlacesLabel.Text = Loc.GetString("wf-ert-prompt-places", ("count", call.Places));
        LeaderButton.Visible = call.HasLeader;

        SignUpButton.OnPressed += _ => SignUpPressed?.Invoke(false);
        LeaderButton.OnPressed += _ => SignUpPressed?.Invoke(true);
        RolesButton.OnPressed += _ => _console.ExecuteCommand("ghostroles");
    }

    public void SetStatus(string message, bool isError)
    {
        StatusLabel.Text = message;
        StatusLabel.FontColorOverride = isError ? Color.Red : null;
    }
}
