using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Audio.InternetSound;

/// <summary>
/// Small radio shown to every player while an admin internet sound plays: who played it, what it is, volume and stop.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class InternetSoundPopup : DefaultWindow
{
    /// <summary>
    /// New volume, 0 to 1, while the slider moves.
    /// </summary>
    public event Action<float>? VolumeChanged;

    public event Action? VolumeReleased;
    public event Action? StopPressed;

    public InternetSoundPopup(string title, string admin, float volume)
    {
        RobustXamlLoader.Load(this);

        AdminLabel.Text = Loc.GetString("wf-internet-sound-popup-played", ("admin", admin));
        TitleLabel.Text = title;
        TitleLabel.ToolTip = title;

        SetVolume(volume);
        VolumeSlider.OnValueChanged += _ =>
        {
            UpdateVolumeLabel();
            VolumeChanged?.Invoke(VolumeSlider.Value / 100f);
        };
        VolumeSlider.OnReleased += _ => VolumeReleased?.Invoke();
        StopButton.OnPressed += _ => StopPressed?.Invoke();
    }

    /// <summary>
    /// Moves the slider without echoing a change back.
    /// </summary>
    public void SetVolume(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume * 100f);
        UpdateVolumeLabel();
    }

    private void UpdateVolumeLabel()
    {
        VolumeLabel.Text = $"{VolumeSlider.Value:0}%";
    }
}
