using System.Linq;
using Content.Client._WF.Administration.GridPower;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Administration;
using Content.Shared._WF.Administration.GridPower;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Administration.UI.GridPower;

/// <summary>
/// SS13's "Make all areas powered/unpowered" for every grid, or one grid picked from the list.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class GridPowerWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private const string AllGrids = "all";

    private readonly GridPowerSystem _gridPower;
    private List<GridPowerInfo> _grids = new();

    public GridPowerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gridPower = _entityManager.System<GridPowerSystem>();
        _gridPower.ListReceived += OnListReceived;
        OnClose += () => _gridPower.ListReceived -= OnListReceived;

        AllPoweredButton.OnPressed += _ => SetPower(true, AllGrids);
        AllUnpoweredButton.OnPressed += _ => SetPower(false, AllGrids);
        RefreshButton.OnPressed += _ => _gridPower.RequestList();
        SearchBar.OnTextChanged += _ => Populate();

        _gridPower.RequestList();
    }

    private void OnListReceived(List<GridPowerInfo> grids)
    {
        _grids = grids.OrderBy(grid => grid.Name, StringComparer.CurrentCultureIgnoreCase).ToList();
        Populate();
    }

    /// <summary>
    /// Rebuilds the grid rows using the current search text.
    /// </summary>
    private void Populate()
    {
        Grids.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var shown = 0;

        foreach (var grid in _grids)
        {
            if (search.Length > 0
                && !grid.Name.ToLowerInvariant().Contains(search)
                && !grid.Map.ToLowerInvariant().Contains(search))
                continue;

            Grids.AddChild(MakeRow(grid, shown++));
        }

        if (_grids.Count == 0)
            Grids.AddChild(new Label { Text = Loc.GetString("wf-grid-power-empty"), Margin = new Thickness(6) });

        CountLabel.Text = Loc.GetString("wf-grid-power-count", ("shown", shown), ("total", _grids.Count));
    }

    private Control MakeRow(GridPowerInfo grid, int index)
    {
        var percent = grid.MaxCharge > 0 ? (int) MathF.Round(grid.Charge / grid.MaxCharge * 100f) : 0;

        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        labels.AddChild(new Label { Text = grid.Name, StyleClasses = { "LabelKeyText" }, ClipText = true });
        labels.AddChild(new Label
        {
            Text = Loc.GetString("wf-grid-power-row",
                ("map", grid.Map),
                ("on", grid.ApcsOn),
                ("apcs", grid.Apcs),
                ("batteries", grid.Batteries),
                ("percent", percent)),
            StyleClasses = { "LabelSubText" },
            ClipText = true,
        });

        var target = grid.Grid.ToString();
        var powered = new Button
        {
            Text = Loc.GetString("wf-grid-power-powered"),
            StyleClasses = { "ButtonSquare" },
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(4, 0),
        };
        powered.OnPressed += _ => SetPower(true, target);

        var unpowered = new ConfirmButton
        {
            Text = Loc.GetString("wf-grid-power-unpowered"),
            ConfirmationText = Loc.GetString("wf-grid-power-confirm"),
            StyleClasses = { "ButtonSquare" },
            VerticalAlignment = VAlignment.Center,
        };
        unpowered.OnPressed += _ => SetPower(false, target);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 3),
        };
        row.AddChild(labels);
        row.AddChild(powered);
        row.AddChild(unpowered);

        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = index % 2 == 0 ? Color.FromHex("#242424") : Color.FromHex("#1E1E1E") },
            Children = { row },
        };
    }

    private void SetPower(bool powered, string target)
    {
        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.GridPower} {(powered ? "on" : "off")} {target} {AnnounceCheck.Pressed}");
    }
}
