using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Administration.UI.Tabs;

/// <summary>
/// Admin menu tab that holds the Wolfgate admin tooling.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WolfgateTab : Control
{
    public WolfgateTab()
    {
        RobustXamlLoader.Load(this);
    }
}
