using System.Linq;
using Content.Shared._WF.Administration;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Administration.UI.SpawnOutfit;

/// <summary>
/// Picks a starting gear outfit to spawn a humanoid with at the target entity.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SpawnOutfitMenu : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;

    private readonly NetEntity _target;
    private StartingGearPrototype? _selected;

    public SpawnOutfitMenu(NetEntity target)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _target = target;

        SearchBar.OnTextChanged += _ => Populate();
        OutfitList.OnItemSelected += OnItemSelected;
        OutfitList.OnItemDeselected += _ => SetSelected(null);
        ConfirmButton.OnPressed += _ => Confirm();

        Populate();
    }

    /// <summary>
    /// Lists starting gear that isn't part of a loadout, filtered by the search text. Same filter as Set Outfit.
    /// </summary>
    private void Populate()
    {
        OutfitList.Clear();
        SetSelected(null);

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var loadoutGears = _prototypeManager.EnumeratePrototypes<LoadoutPrototype>()
            .Select(loadout => loadout.StartingGear.ToString())
            .ToHashSet();

        foreach (var gear in _prototypeManager.EnumeratePrototypes<StartingGearPrototype>().OrderBy(gear => gear.ID))
        {
            if (loadoutGears.Contains(gear.ID))
                continue;
            if (search.Length > 0 && !gear.ID.ToLowerInvariant().Contains(search))
                continue;

            OutfitList.Add(new ItemList.Item(OutfitList) { Metadata = gear, Text = gear.ID });
        }
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        SetSelected((StartingGearPrototype) args.ItemList[args.ItemIndex].Metadata!);
    }

    private void SetSelected(StartingGearPrototype? gear)
    {
        _selected = gear;
        ConfirmButton.Disabled = gear == null;
    }

    private void Confirm()
    {
        if (_selected == null)
            return;

        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.SpawnOutfit} {_target} \"{_selected.ID}\" {ControlCheck.Pressed}");
        Close();
    }
}
