using System.Linq;
using Content.Client.Administration.Managers;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared._WF.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Administration.UI.VesselSpawn;

/// <summary>
/// Lists every spawnable vessel prototype and spawns the chosen one via the spawnvessel command.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class VesselSpawnWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IClientAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private readonly List<VesselPrototype> _vessels = new();
    private readonly List<VesselSize> _sizes = new();
    private readonly List<string> _owners = new();
    private VesselSize? _sizeFilter;

    public VesselSpawnWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadVessels();
        PopulateSizes();
        PopulateOwners();

        SearchBar.OnTextChanged += _ => PopulateVessels();
        SizeFilter.OnItemSelected += OnSizeSelected;
        OwnerSelect.OnItemSelected += args => OwnerSelect.SelectId(args.Id);

        // Keep the owner picker in step with players joining and leaving.
        _playerManager.PlayerListUpdated += PopulateOwners;
        OnClose += () => _playerManager.PlayerListUpdated -= PopulateOwners;

        PopulateVessels();
    }

    /// <summary>
    /// Collects every non-abstract vessel prototype, sorted by name.
    /// </summary>
    private void LoadVessels()
    {
        _vessels.Clear();
        _vessels.AddRange(_prototypeManager.EnumeratePrototypes<VesselPrototype>().Where(vessel => !vessel.Abstract));
        _vessels.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
    }

    /// <summary>
    /// Fills the size filter with "All" plus every size present in the vessel list.
    /// </summary>
    private void PopulateSizes()
    {
        _sizes.Clear();
        _sizes.Add(VesselSize.All);
        _sizes.AddRange(_vessels.Select(vessel => vessel.Category).Distinct().OrderBy(size => size));

        SizeFilter.Clear();
        for (var i = 0; i < _sizes.Count; i++)
        {
            SizeFilter.AddItem(Loc.GetString($"shipyard-console-category-{_sizes[i]}"), i);
        }
    }

    /// <summary>
    /// Fills the owner picker with "None" plus every connected player. Id 0 is none, id n is _owners[n - 1].
    /// </summary>
    private void PopulateOwners()
    {
        // Keep the current pick if that player is still connected.
        var selectedId = OwnerSelect.SelectedId;
        var selected = selectedId > 0 && selectedId <= _owners.Count ? _owners[selectedId - 1] : null;

        _owners.Clear();
        _owners.AddRange(_playerManager.Sessions.Select(session => session.Name).OrderBy(name => name));

        OwnerSelect.Clear();
        OwnerSelect.AddItem(Loc.GetString("wf-vessel-spawn-owner-none"), 0);
        for (var i = 0; i < _owners.Count; i++)
        {
            OwnerSelect.AddItem(_owners[i], i + 1);
        }

        var index = selected == null ? -1 : _owners.IndexOf(selected);
        OwnerSelect.SelectId(index >= 0 ? index + 1 : 0);
    }

    private void OnSizeSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SizeFilter.SelectId(args.Id);
        _sizeFilter = args.Id == 0 ? null : _sizes[args.Id];
        PopulateVessels();
    }

    /// <summary>
    /// Rebuilds the vessel rows using the current search text and size filter.
    /// </summary>
    private void PopulateVessels()
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var canSpawn = _adminManager.CanCommand(WolfgateAdminCommands.SpawnVessel);
        var shown = 0;

        foreach (var vessel in _vessels)
        {
            if (_sizeFilter != null && vessel.Category != _sizeFilter)
                continue;
            if (search.Length > 0 && !Matches(vessel, search))
                continue;

            var row = new VesselSpawnRow(vessel, canSpawn);
            row.OnSpawnPressed += OnSpawnPressed;
            Vessels.AddChild(row);
            shown++;
        }

        CountLabel.Text = Loc.GetString("wf-vessel-spawn-count", ("shown", shown), ("total", _vessels.Count));
    }

    private static bool Matches(VesselPrototype vessel, string search)
    {
        return vessel.Name.ToLowerInvariant().Contains(search)
               || vessel.ID.ToLowerInvariant().Contains(search);
    }

    private void OnSpawnPressed(VesselPrototype vessel)
    {
        var owner = OwnerSelect.SelectedId == 0 ? string.Empty : $" \"{_owners[OwnerSelect.SelectedId - 1]}\"";
        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.SpawnVessel} \"{vessel.ID}\"{owner}");
    }
}
