using System.Linq;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Administration.UI.VesselSpawn;

/// <summary>
/// One vessel in the spawn list: name, ID, basic stats, description and a spawn button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class VesselSpawnRow : PanelContainer
{
    public event Action<VesselPrototype>? OnSpawnPressed;

    public VesselSpawnRow(VesselPrototype vessel, bool canSpawn)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = vessel.Name;
        IdLabel.Text = vessel.ID;
        StatsLabel.Text = BuildStats(vessel);
        DescriptionLabel.Text = vessel.Description;
        DescriptionLabel.Visible = vessel.Description.Length > 0;

        SpawnButton.Disabled = !canSpawn;
        SpawnButton.OnPressed += _ => OnSpawnPressed?.Invoke(vessel);
    }

    /// <summary>
    /// Size, price, classes and engines on one line, reusing the shipyard's loc strings.
    /// </summary>
    private static string BuildStats(VesselPrototype vessel)
    {
        var none = Loc.GetString("wf-vessel-spawn-none");
        var size = Loc.GetString($"shipyard-console-category-{vessel.Category}");
        var classes = vessel.Classes.Count > 0
            ? string.Join(", ", vessel.Classes.Select(c => Loc.GetString($"shipyard-console-class-{c}")))
            : none;
        var engines = vessel.Engines.Count > 0
            ? string.Join(", ", vessel.Engines.Select(e => Loc.GetString($"shipyard-console-engine-{e}")))
            : none;

        return Loc.GetString("wf-vessel-spawn-stats",
            ("size", size),
            ("price", BankSystemExtensions.ToSpesoString(vessel.Price)),
            ("classes", classes),
            ("engines", engines));
    }
}
